version: '3'
services:
  hasto_gateway:
    build: .
    depends_on:
      - redis
      - mongoDB
    ports:
      - '8088:3000'
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - backend
  mongoDB:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
networks:
  backend:
