version: '3'
services:
  hasto_gateway:
    build: .
    depends_on:
      - redis
      - mongoDB
    ports:
      - '8088:3000'
    networks:
      - hasto
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - hasto
  mongoDB:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - hasto
  ipfs_host:
    image: ipfs/go-ipfs
    ports:
      - '8080:8080'
      - '5001:5001'
      - '4001:4001'
    networks:
      - hasto
    volumes:
      - ./ipfs_data/:/home/ipfs/ipfs_data
      - ./ipfs_staging/:/home/ipfs/ipfs_staging
networks:
  hasto:
